import test from "ava"
import CezeriClient from ".."

const API_CREDENTIALS = {
  apiBaseUrl: "/api",
  apiToken: "<test>",
}

const AJAX_CREDENTIALS = {
  ajaxBaseUrl: "/ajax",
}

test("api structure", t => {
  const api = new CezeriClient(API_CREDENTIALS)
  t.is(typeof api.products.list, "function")
  t.is(typeof api.products.retrieve, "function")
  t.is(typeof api.products.create, "function")
  t.is(typeof api.products.update, "function")
  t.is(typeof api.products.delete, "function")
  t.is(typeof api.products.skuExists, "function")
  t.is(typeof api.products.slugExists, "function")
  t.is(typeof api.products.options.list, "function")
  t.is(typeof api.products.options.retrieve, "function")
  t.is(typeof api.products.options.create, "function")
  t.is(typeof api.products.options.update, "function")
  t.is(typeof api.products.options.delete, "function")
  t.is(typeof api.products.options.values.list, "function")
  t.is(typeof api.products.options.values.retrieve, "function")
  t.is(typeof api.products.options.values.create, "function")
  t.is(typeof api.products.options.values.update, "function")
  t.is(typeof api.products.options.values.delete, "function")
  t.is(typeof api.products.variants.list, "function")
  t.is(typeof api.products.variants.create, "function")
  t.is(typeof api.products.variants.update, "function")
  t.is(typeof api.products.variants.delete, "function")
  t.is(typeof api.products.variants.setOption, "function")
  t.is(typeof api.products.images.list, "function")
  t.is(typeof api.products.images.update, "function")
  t.is(typeof api.products.images.upload, "function")
  t.is(typeof api.products.images.delete, "function")
  t.is(typeof api.productCategories.list, "function")
  t.is(typeof api.productCategories.retrieve, "function")
  t.is(typeof api.productCategories.create, "function")
  t.is(typeof api.productCategories.update, "function")
  t.is(typeof api.productCategories.delete, "function")
  t.is(typeof api.productCategories.uploadImage, "function")
  t.is(typeof api.productCategories.deleteImage, "function")
  t.is(typeof api.customers.list, "function")
  t.is(typeof api.customers.retrieve, "function")
  t.is(typeof api.customers.create, "function")
  t.is(typeof api.customers.update, "function")
  t.is(typeof api.customers.delete, "function")
  t.is(typeof api.customers.createAddress, "function")
  t.is(typeof api.customers.updateAddress, "function")
  t.is(typeof api.customers.deleteAddress, "function")
  t.is(typeof api.customers.setDefaultBillingAddress, "function")
  t.is(typeof api.customers.setDefaultShippingAddress, "function")
  t.is(typeof api.customerGroups.list, "function")
  t.is(typeof api.customerGroups.retrieve, "function")
  t.is(typeof api.customerGroups.create, "function")
  t.is(typeof api.customerGroups.update, "function")
  t.is(typeof api.customerGroups.delete, "function")
  t.is(typeof api.orders.list, "function")
  t.is(typeof api.orders.retrieve, "function")
  t.is(typeof api.orders.create, "function")
  t.is(typeof api.orders.update, "function")
  t.is(typeof api.orders.delete, "function")
  t.is(typeof api.orders.recalculate, "function")
  t.is(typeof api.orders.checkout, "function")
  t.is(typeof api.orders.cancel, "function")
  t.is(typeof api.orders.close, "function")
  t.is(typeof api.orders.updateBillingAddress, "function")
  t.is(typeof api.orders.updateShippingAddress, "function")
  t.is(typeof api.orders.getPaymentFormSettings, "function")
  t.is(typeof api.orders.discounts.create, "function")
  t.is(typeof api.orders.discounts.update, "function")
  t.is(typeof api.orders.discounts.delete, "function")
  t.is(typeof api.orders.transactions.create, "function")
  t.is(typeof api.orders.transactions.update, "function")
  t.is(typeof api.orders.transactions.delete, "function")
  t.is(typeof api.orders.items.create, "function")
  t.is(typeof api.orders.items.update, "function")
  t.is(typeof api.orders.items.delete, "function")
  t.is(typeof api.orderStatuses.list, "function")
  t.is(typeof api.orderStatuses.retrieve, "function")
  t.is(typeof api.orderStatuses.create, "function")
  t.is(typeof api.orderStatuses.update, "function")
  t.is(typeof api.orderStatuses.delete, "function")
  t.is(typeof api.shippingMethods.list, "function")
  t.is(typeof api.shippingMethods.retrieve, "function")
  t.is(typeof api.shippingMethods.create, "function")
  t.is(typeof api.shippingMethods.update, "function")
  t.is(typeof api.shippingMethods.delete, "function")
  t.is(typeof api.paymentMethods.list, "function")
  t.is(typeof api.paymentMethods.retrieve, "function")
  t.is(typeof api.paymentMethods.create, "function")
  t.is(typeof api.paymentMethods.update, "function")
  t.is(typeof api.paymentMethods.delete, "function")
  t.is(typeof api.paymentGateways.retrieve, "function")
  t.is(typeof api.paymentGateways.update, "function")
  t.is(typeof api.sitemap.list, "function")
  t.is(typeof api.sitemap.retrieve, "function")
  t.is(typeof api.theme.export, "function")
  t.is(typeof api.theme.install, "function")
  t.is(typeof api.theme.settings.retrieve, "function")
  t.is(typeof api.theme.settings.update, "function")
  t.is(typeof api.theme.settings.retrieveSchema, "function")
  t.is(typeof api.theme.assets.uploadFile, "function")
  t.is(typeof api.theme.assets.deleteFile, "function")
  t.is(typeof api.theme.placeholders.list, "function")
  t.is(typeof api.theme.placeholders.retrieve, "function")
  t.is(typeof api.theme.placeholders.create, "function")
  t.is(typeof api.theme.placeholders.update, "function")
  t.is(typeof api.theme.placeholders.delete, "function")
  t.is(typeof api.countries.list, "function")
  t.is(typeof api.currencies.list, "function")
  t.is(typeof api.text.list, "function")
  t.is(typeof api.settings.retrieve, "function")
  t.is(typeof api.settings.update, "function")
  t.is(typeof api.settings.retrieveEmailSettings, "function")
  t.is(typeof api.settings.updateEmailSettings, "function")
  t.is(typeof api.settings.retrieveEmailTemplate, "function")
  t.is(typeof api.settings.updateEmailTemplate, "function")
  t.is(typeof api.settings.uploadLogo, "function")
  t.is(typeof api.settings.deleteLogo, "function")
  t.is(typeof api.checkoutFields.list, "function")
  t.is(typeof api.checkoutFields.retrieve, "function")
  t.is(typeof api.checkoutFields.update, "function")
  t.is(typeof api.pages.list, "function")
  t.is(typeof api.pages.retrieve, "function")
  t.is(typeof api.pages.create, "function")
  t.is(typeof api.pages.update, "function")
  t.is(typeof api.pages.delete, "function")
  t.is(typeof api.tokens.list, "function")
  t.is(typeof api.tokens.retrieve, "function")
  t.is(typeof api.tokens.create, "function")
  t.is(typeof api.tokens.update, "function")
  t.is(typeof api.tokens.delete, "function")
  t.is(typeof api.redirects.list, "function")
  t.is(typeof api.redirects.retrieve, "function")
  t.is(typeof api.redirects.create, "function")
  t.is(typeof api.redirects.update, "function")
  t.is(typeof api.redirects.delete, "function")
  t.is(typeof api.webhooks.list, "function")
  t.is(typeof api.webhooks.retrieve, "function")
  t.is(typeof api.webhooks.create, "function")
  t.is(typeof api.webhooks.update, "function")
  t.is(typeof api.webhooks.delete, "function")
  t.is(typeof api.files.list, "function")
  t.is(typeof api.files.upload, "function")
  t.is(typeof api.files.delete, "function")
  t.is(typeof api.apps.settings.retrieve, "function")
  t.is(typeof api.apps.settings.update, "function")
})

test("ajax structure", t => {
  const api = new CezeriClient(AJAX_CREDENTIALS)
  t.is(typeof api.ajax.products.list, "function")
  t.is(typeof api.ajax.products.retrieve, "function")
  t.is(typeof api.ajax.products.create, "function")
  t.is(typeof api.ajax.products.update, "function")
  t.is(typeof api.ajax.products.delete, "function")
  t.is(typeof api.ajax.products.skuExists, "function")
  t.is(typeof api.ajax.products.slugExists, "function")
  t.is(typeof api.ajax.sitemap.list, "function")
  t.is(typeof api.ajax.sitemap.retrieve, "function")
  t.is(typeof api.ajax.cart.retrieve, "function")
  t.is(typeof api.ajax.cart.update, "function")
  t.is(typeof api.ajax.cart.checkout, "function")
  t.is(typeof api.ajax.cart.updateBillingAddress, "function")
  t.is(typeof api.ajax.cart.updateShippingAddress, "function")
  t.is(typeof api.ajax.cart.addItem, "function")
  t.is(typeof api.ajax.cart.updateItem, "function")
  t.is(typeof api.ajax.cart.deleteItem, "function")
  t.is(typeof api.ajax.login.retrieve, "function")
  t.is(typeof api.ajax.register.retrieve, "function")
  t.is(typeof api.ajax.account.retrieve, "function")
  t.is(typeof api.ajax.account.update, "function")
  t.is(typeof api.ajax.forgotPassword.retrieve, "function")
  t.is(typeof api.ajax.forgotPassword.update, "function")
  t.is(typeof api.ajax.resetPassword.retrieve, "function")
  t.is(typeof api.ajax.resetPassword.update, "function")
  t.is(typeof api.ajax.countries.list, "function")
  t.is(typeof api.ajax.currencies.list, "function")
  t.is(typeof api.ajax.shippingMethods.list, "function")
  t.is(typeof api.ajax.paymentMethods.list, "function")
  t.is(typeof api.ajax.paymentFormSettings.retrieve, "function")
  t.is(typeof api.ajax.pages.list, "function")
  t.is(typeof api.ajax.pages.retrieve, "function")
  t.is(typeof api.ajax.pages.create, "function")
  t.is(typeof api.ajax.pages.update, "function")
  t.is(typeof api.ajax.pages.delete, "function")
})

test("webstore structure", t => {
  const api = new CezeriClient(AJAX_CREDENTIALS)
  t.is(typeof api.webstore.account.retrieve, "function")
  t.is(typeof api.webstore.account.update, "function")
  t.is(typeof api.webstore.account.updateDeveloper, "function")
  t.is(typeof api.webstore.services.list, "function")
  t.is(typeof api.webstore.services.retrieve, "function")
  t.is(typeof api.webstore.services.enable, "function")
  t.is(typeof api.webstore.services.disable, "function")
  t.is(typeof api.webstore.services.settings.retrieve, "function")
  t.is(typeof api.webstore.services.settings.update, "function")
  t.is(typeof api.webstore.services.actions.call, "function")
  t.is(typeof api.webstore.services.logs.list, "function")
})

test("static methods", t => {
  t.is(typeof CezeriClient.authorize, "function")
  t.is(typeof CezeriClient.authorizeInWebStore, "function")
})
