name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue is stale."
          stale-pr-message: "This pull request is stale. Please, if stayed any longer will be closed."
          stale-issue-label: "No activity"
          stale-pr-label: "No activity"
