"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CATEGORIES_REQUEST = "CATEGORIES_REQUEST";
exports.CATEGORIES_RECEIVE = "CATEGORIES_RECEIVE";
exports.CATEGORIES_FAILURE = "CATEGORIES_FAILURE";
exports.CATEGORIES_SELECT = "CATEGORIES_SELECT";
exports.CATEGORIES_DESELECT = "CATEGORIES_DESELECT";
exports.CATEGORY_UPDATE_REQUEST = "CATEGORY_UPDATE_REQUEST";
exports.CATEGORY_UPDATE_SUCCESS = "CATEGORY_UPDATE_SUCCESS";
exports.CATEGORY_UPDATE_FAILURE = "CATEGORY_UPDATE_FAILURE";
exports.CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS";
exports.CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
exports.CATEGORY_MOVE_UPDOWN_SUCCESS = "CATEGORY_MOVE_UPDOWN_SUCCESS";
exports.CATEGORY_REPLACE_SUCCESS = "CATEGORY_REPLACE_SUCCESS";
exports.CATEGORY_IMAGE_UPLOAD_START = "CATEGORY_IMAGE_UPLOAD_START";
exports.CATEGORY_IMAGE_UPLOAD_END = "CATEGORY_IMAGE_UPLOAD_END";
//# sourceMappingURL=actionTypes.js.map